AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - node_modules/**/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
